### ISSUE TITLE
translator return 429  or null

### ISSUE THREAD

**Issue by jatin-rajput** [gabrielpacheco23/google-translator#10]
my code--
final translator = new GoogleTranslator();
//  final input = "Здравствуйте. Ты в порядке?";
  _onTextChanged(String text) {
    if (text != "") {
      translator.translate(text, from: 'en', to: 'ru').then((s) {
        print(s);
      });}

give me suggestion .. advance thanks.. 
I think this is due to overload..

it is working well .. but in night i am try to translate a word it shows 429 error .. but i am sends only 5-10 request in 4 hours,,
i found this.. Google Translate Api has a default billable limit of 5 requests/second/user and 200,000 requests/day.

**Comment by gabrielpacheco23** [comment]
Have you tried to translate these texts in a short time? Try putting some delay between the translations.
If the error persists, comment below.

**Comment by ajnaf** [comment]
same issue.
 How to add delay??
thank you

**Comment by gabrielpacheco23** [comment]
> same issue.
> How to add delay??
> thank you

You can put a `await Future.delayed(milliseconds: 500)` between each translation, for example.

**Comment by jatin-rajput** [comment]
your  translator package is awesome....

**Comment by gabrielpacheco23** [comment]
> your translator package is awesome....

Thank you very much! Did you solve your problem?

**Comment by jatin-rajput** [comment]
Yes my problem is solved..thanks your suggestions

**Comment by pqtrong17** [comment]
> > your translator package is awesome....
> 
> Thank you very much! Did you solve your problem?

I inadvertent sent too many request. I wait 30 minutes and try again but still get 429 Error. How to fix it?
